#ifndef _DRIVER_PCI_PCI_CONFIG_H
#define _DRIVER_PCI_PCI_CONFIG_H

#define PCI_IO_CONFADD 0xcf8
#define PCI_IO_CONFDATA 0xcfc

#define PCI_IO_CONF_CONE 31
#define PCI_IO_CONF_BUSNUM 16
#define PCI_IO_CONF_DEVNUM 11
#define PCI_IO_CONF_FUNCNUM 8
#define PCI_IO_CONF_REGNUM 2

#define PCI_CONF_VENDOR 0x0
#define PCI_CONF_DEVICE 0x2
#define PCI_CONF_COMMAND 0x4
#define PCI_CONF_STATUS 0x6
#define PCI_CONF_CLASS 0xb
#define PCI_CONF_SUBCLASS 0xa
#define PCI_CONF_PROGIF 0x9
#define PCI_CONF_BAR 0x10
#define PCI_CONF_INTR_LINE 0x3c
#define PCI_CONF_INTR_PIN 0x3d

#define PCI_CONTROL_IO 1
#define PCI_CONTROL_MEMORY 2
#define PCI_CONTROL_BUS_MASTER 4
#define PCI_CONTROL_SPECIAL_CYCLES 8
#define PCI_CONTROL_MEMORY_INVAILDATE 16
#define PCI_CONTROL_VGA_PALETTE 32
#define PCI_CONTROL_PARITY_ERROR 64
#define PCI_CONTROL_SERR 256
#define PCI_CONTROL_FAST_BACK 512
#define PCI_CONTROL_INTERRUPT_DISABLE 1024

#define PCI_STATUS_INTERRUPT 8
#define PCI_STATUS_CAPABILITIES_LIST 16
#define PCI_STATUS_66MHZ 32
#define PCI_STATUS_FAST_BACK 128
#define PCI_STATUS_MASTER_DATA_PARITY_ERROR 256
#define PCI_STATUS_SIGNALED_TARGET_ABORT 2048
#define PCI_STATUS_RECEIVED_TARGET_ABORT 4096
#define PCI_STATUS_RECEIVED_MASTER_ERROR 8192
#define PCI_STATUS_SIGNALED_SYSTEM_ERROR 16384
#define PCI_STATUS_DETECTED_PARITY_ERROR 32768

#endif
