all:
	$(MAKE) -C init install
	$(MAKE) -C sh install
	$(MAKE) -C dir install
	$(MAKE) -C cat install
	$(MAKE) -C lscpu install
	$(MAKE) -C wm install
	$(MAKE) -C desktop install

.PHONY: clean
clean:
	$(MAKE) -C init clean
	$(MAKE) -C sh clean
	$(MAKE) -C dir clean
	$(MAKE) -C cat clean
	$(MAKE) -C lscpu clean
	$(MAKE) -C wm clean
	$(MAKE) -C desktop clean
