all:
	$(MAKE) -C init install
	$(MAKE) -C sh install
	$(MAKE) -C dir install
	$(MAKE) -C cat install

.PHONY: clean
clean:
	$(MAKE) -C init clean
	$(MAKE) -C sh clean
	$(MAKE) -C dir clean
	$(MAKE) -C cat clean
