all:
	$(MAKE) -C init install
	$(MAKE) -C sh install
	$(MAKE) -C dir install
	$(MAKE) -C cat install
	$(MAKE) -C lscpu install
	$(MAKE) -C wm install
	$(MAKE) -C desktop install
	$(MAKE) -C termemu install
	$(MAKE) -C mkdir install
	$(MAKE) -C rm install
	$(MAKE) -C about install
	$(MAKE) -C kmod install
	$(MAKE) -C lspci install
	$(MAKE) -C reboot install
	$(MAKE) -C shutdown install
	$(MAKE) -C date install
	$(MAKE) -C devmgr install
	$(MAKE) -C imgview install
	$(MAKE) -C ls install

.PHONY: clean
clean:
	$(MAKE) -C init clean
	$(MAKE) -C sh clean
	$(MAKE) -C dir clean
	$(MAKE) -C cat clean
	$(MAKE) -C lscpu clean
	$(MAKE) -C wm clean
	$(MAKE) -C desktop clean
	$(MAKE) -C termemu clean
	$(MAKE) -C mkdir clean
	$(MAKE) -C rm clean
	$(MAKE) -C about clean
	$(MAKE) -C kmod clean
	$(MAKE) -C lspci clean
	$(MAKE) -C reboot clean
	$(MAKE) -C shutdown clean
	$(MAKE) -C date clean
	$(MAKE) -C devmgr clean
	$(MAKE) -C imgview clean
	$(MAKE) -C ls clean
