#ifndef _COMMON_ERRORCODE_H
#define _COMMON_ERRORCODE_H

#define ERROR_INVAILD -1
#define ERROR_NOT_EXIST -2
#define ERROR_EXIST -3
#define ERROR_NOT_FILE -4
#define ERROR_NOT_DIRECTORY -5
#define ERROR_READ_FAIL -6
#define ERROR_OUT_OF_SPACE -7
#define ERROR_WRITE_FAIL -8

#endif
